### ISSUE TITLE
Probably stupid question

### ISSUE THREAD

**Issue by ngocphamm** [RRethy/nvim-treesitter-textsubjects#30]
Hi. I'm very new to using vim/neovim at higher level rather than basic editing and `:w` to save.

I've been trying to jump into neovim with Lua, and I found this plugin, being used with treesitter. However, I'm wondering what this one does that is significantly different/better from the default `incremental_selection` feature built into treesitter.

With `incremental_selection`, I use `v` to start selecting a character, or more, then say I press whatever the key mapped to do `node_incremental` to continue to increment the selection. That eventually select a line, then an `if` inner block, then the `if` outer block, then the function, etc.

With `textsubjects`, pressing `.` by default, would select the whole line, then the `if` outer block. It takes 2 key strokes instead of 5-6 like above.

So is the main point here is to save the key strokes, or there's something obvious to anyone else and not to me?

Again, I'm totally new to any of this, so I'm sorry if this is too naive of a question or something. Not that I don't appreciate the work here. I just want to understand more of what is going on.

Also, in the README of the plugin, there's a mentions `lookahead` feature from `textobjects` plugin, but in the config of the author of `packer.nvim`, I see it also being used for this plugin. I'm a little confused if it's available in this plugin as well, or not. Not that I really understand what it does, though...

https://github.com/wbthomason/dotfiles/blob/linux/neovim/.config/nvim/plugin/treesitter.lua#L19

**Comment by RRethy** [comment]
> So is the main point here is to save the key strokes

Partly yes, the whole concept of scope in incremental_selection is based on the levels of the concrete syntax tree which isn't what most programmers want when they are incrementing their text selection.

The point of textsubjects was to eliminate the many keymaps from nvim-treesitter-textobjects. Whereas typically you would have a textobject for a function, another for a class, another for an interface, etc. With textsubjects you have a single mapping which handles all of them depending on where you are. The selection expansion was just a bonus feature since e.g. there are times you are on a function but want the whole class. 

Textsubjects also give the programmer the ability to defined their own selections, for example, say I want to expand on if-statements, for-loops, and while-loops, I could do that with a single treesitter query and everything would just work.

textsubjects also handle changing between visual mode and visual-line mode automatically.

As for the author of packer.nvim and his config, it's wrong. I'm confused by it too, it also has some keymaps which are invalid so I'm assuming he doesn't use that functionality and thus hasn't noticed. Here's my treesitter config:

```
treesitter.setup {
    highlight = {
        enable = true,
    },
    playground = {
        enable = true,
    },
    textobjects = {
        select = {
            enable = true,
            lookahead = true,
            keymaps = {
                ["ia"] = "@parameter.inner",
                ["aa"] = "@parameter.outer",
            },
            include_surrounding_whitespace = true,
        },
        move = {
            enable = true,
            goto_next_start = {
                [']m'] = '@function.outer',
            },
            goto_previous_start = {
                ['[m'] = '@function.outer',
            },
        },
    },
    endwise = {
        enable = true,
    },
    textsubjects = {
        enable = true,
        prev_selection = ',',
        keymaps = {
            ['.'] = 'textsubjects-smart',
            [';'] = 'textsubjects-container-outer',
            ['i;'] = 'textsubjects-container-inner',
        },
    },
}
```
